Determining passed tests using exit code

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,8 +1,31 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+# Copyright 2017 The TIE Authors. All Rights Reserved.
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#      http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS-IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+# Usage:
+#
+#     Not meant for manual use
+#     Runs automatically before a git push command is executed
+#     Behaviour can be set up using "bash scripts/setup_hooks.sh"
 
 echo "Running linter tests"
-lines=$(sh scripts/run_linter.sh | wc -l)
-if [ $lines -eq 1 ]; then
+sh scripts/run_linter.sh
+
+# Checking exit code returned
+if [ $? -eq 0 ]
+then
     echo "Linter tests passed"
 else
     # Assign standard input to keyboard
@@ -14,6 +37,9 @@ else
         [Nn]* ) echo "Not pushing changes"; exit 1;;
         * ) echo "Invalid input";;
     esac
+
+    # Close standard input
+    exec <&-
 fi
 
 echo "Running karma tests"
